name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: ./.github/actions/pnpm-setup

      - run: pnpm lint
        if: always()
      - run: pnpm test:types
        if: always()
      - run: pnpm build
        if: always()
      # - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v3
